[package]
name = "crash_ide_widget"
version = "0.1.0-rc.1"
edition = "2021"

[dependencies]
bevy = { workspace = true, features = ["bevy_ui"] }
ab_glyph = { workspace = true }

crash_ide_clipboard = { workspace = true }