[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
bevy = { version = "0.13.2", default-features = false }
bevy_file_dialog = "0.5.0"
serde = "^1.0"
serde_json = "^1.0"
homedir = "^0.2"

editor_state = { path = "crates/editor_state" }
editor_config = { path = "crates/editor_config" }
editor_ui = { path = "crates/editor_ui" }
editor_widget = { path = "crates/editor_widget" }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3