[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
bevy = "0.13.2"
serde = "^1.0"
serde_json = "^1.0"

editor_state = { path = "crates/editor_state" }
editor_config = { path = "crates/editor_config" }
editor_ui = { path = "crates/editor_ui" }