[package]
name = "editor_ui"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
bevy_file_dialog = { workspace = true }
editor_state = { workspace = true }
editor_config = { workspace = true }
editor_widget = { workspace = true }