[package]
name = "editor_file"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true, features = ["bevy_ui"] }
open = { workspace = true }
editor_config = { workspace = true }
editor_widget = { workspace = true }
editor_assets = { workspace = true }