[package]
name = "crash_ide_code_view"
version = "0.1.0-rc.1"
edition = "2021"

[dependencies]
bevy = { workspace = true }
crash_ide_widget = { workspace = true }
crash_ide_util = { workspace = true }