[package]
name = "editor_config"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
editor_state = { workspace = true }
homedir = { workspace = true }